all:
  children:
    routers:
      hosts:
        isp-router:
          ansible_host: 203.0.113.1
        edge-router:
          ansible_host: 10.118.10.3
        core-router:
          ansible_host: 10.118.10.1
    switches:
      hosts:
        meraki-sw:
          ansible_host: 10.118.10.2
        huawei-server-sw:
          ansible_host: 10.118.10.20
    firewalls:
      hosts:
        nci-firewall:
          ansible_host: 10.118.10.4